### ISSUE TITLE
Playground device detection

### ISSUE THREAD

**Issue by Comodore125** [bigclownlabs/bch-playground#11]
Hi,
I got some issues. 
On win 11 - I dont even see my usb radio dongle. 
I see it in vmware debian but flashing firmware did not work. 
So I am here without any progress possible. 
I also got raspbian by hardwario (hub) and there it also does not detect the dongle. 
I am out of ideas. I am using latest version of hardwario playground.

**Comment by Comodore125** [comment]
I was able to flash firmware via CLI in raspberry pi hub according to documentation. But I cant see the USB device being detected anywhere.

**Comment by Comodore125** [comment]
Finaly I made it work. Had to not only restart the rasperry pi. but to unplug POE power wait couple seconds and plug the power again. Then the USB dongle got dettected and I paired the other part of hardwario tower (some sensor) However, it was complicated to make this run. Would be really good if the playground sends some recommendation what to do. There is link currently for that but it does not have the relevant info.

**Comment by Comodore125** [comment]
This link does not work: To learn more about HARDWARIO Playground, visit the [Desktop Programming section](https://docs.hardwario.com/tower/category/desktop-programming).

**Comment by Comodore125** [comment]
To learn more about HARDWARIO Playground, visit the [Desktop Programming section](https://docs.hardwario.com/tower/getting-started/category/desktop-programming). --- This link does not work here: https://docs.hardwario.com/tower/getting-started/desktop-programming/

**Comment by hubpav** [comment]
@Comodore125 Thanks for reporting the broken link issue. We will fix that ASAP. I am glad it worked in the end. Yes, we should improve the experience to make it easier.

**Comment by SmejkalJakub** [comment]
Hello @Comodore125 I fixed the link in the documentation. Thanks for the heads up. If you run into any other issues, feel free to contact us again.
