### ISSUE TITLE
Windows 10 Firewall block

### ISSUE THREAD

**Issue by owarek** [bigclownlabs/bch-playground#3]
I have playground on my Windows 10 machine and it works except when I try to connect to outside MQTT server it can not do that. When I disabled Windows firewall it works.  I have bigclown playground.exe in allowed programs but it still does not work.
![image](https://user-images.githubusercontent.com/5362973/49930330-a29c5680-fec4-11e8-92e0-61daa2eabe32.png)

**Comment by hubpav** [comment]
Hi, thanks for pointing this out.

If the firewall is blocking traffic to external MQTT server, there is not much we can do about it. Just for curiosity - there are 2 checkboxes but I do not see their headline. By any chance, isn't the right checkbox for public network communication and your network identified as a public one? Anyway, it is definitely a matter of Windows Firewall configuration and there is definitely a way how to let 1883 TCP port pass to external IPs.

Did you solve it somehow?

**Comment by owarek** [comment]
Well it is weird. I have only one connection to my PC (wired ethernet marked as private). When I disable firewall totaly or check the other box for public networks it works. So my actuall solution is checked public network checkbox. I know this is not in your competence but I just wanted to point this out.

Keep the good work and have a nice day!
