### ISSUE TITLE
Hardwario playground v1.2.0 and v1.2.1 missing HARDWARIO Playground.exe after instalation, Windows 10

### ISSUE THREAD

**Issue by MatousSloboda** [bigclownlabs/bch-playground#5]
Hi @blavka it looks like there is some problem in latest releases of hardwario playground v1.2.0 and v1.2.1 on Windows 10.
There is missing HARDWARIO Playground.exe file after installation of both 32 and 64 bit version of the playground setup on Windows 10 V1903.
There is also problem running portable version - after opening program no windows appear and application exit with no warning (according to a task manager).

**Comment by blavka** [comment]
Hi,
@hubmartin tried win10 and me now and everything worked. I try version v1.2.1 install and portabel for 64bit. And portable for 32bit.
Do you have any antivirus? Can you try disable him, and try again?

**Comment by MatousSloboda** [comment]
You are right. 
I have tried latest 64bit portable on another windows installation and it launched correctly.
Maybe there are some file fragment and / or config from previous version which wasn't correctly uninstalled.
Thank you for your support and prompt response.

**Comment by blavka** [comment]
np
